### ISSUE TITLE
Cotisations manquantes

### ISSUE THREAD

**Issue by Morendil** [sgmap/syso#48]
Par rapport à la V1 il manque encore des cotisations patronales et des aides:
- [x] le taux de versement transport (#51)
- [x] le taux AT/MP (#60)
- [x] la formation professionnelle (#53)
- [x] la taxe d'apprentissage (#50)
- [x] la cotisation pénibilité (#54)
- [x] la taxe sur les salaires (#59)
- [x] le statut JEI (#56)

Dépendances : #49 #47

**Comment by Morendil** [comment]
En prod :tada: at https://embauche.beta.gouv.fr/simu/Salaire (soft launch)
